# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Mahalanobis <- function(x, center, cov) {
    .Call('_MulticastNetwork_Mahalanobis', PACKAGE = 'MulticastNetwork', x, center, cov)
}

ei <- function(M) {
    .Call('_MulticastNetwork_ei', PACKAGE = 'MulticastNetwork', M)
}

dmvnorm_arma <- function(x, mean, sigma) {
    .Call('_MulticastNetwork_dmvnorm_arma', PACKAGE = 'MulticastNetwork', x, mean, sigma)
}

rmvnorm_arma <- function(n, mu, Sigma) {
    .Call('_MulticastNetwork_rmvnorm_arma', PACKAGE = 'MulticastNetwork', n, mu, Sigma)
}

transpose <- function(x) {
    .Call('_MulticastNetwork_transpose', PACKAGE = 'MulticastNetwork', x)
}

tabulateC <- function(x, max) {
    .Call('_MulticastNetwork_tabulateC', PACKAGE = 'MulticastNetwork', x, max)
}

Timepartsum <- function(mumat, sigma_tau, senders, timestamps) {
    .Call('_MulticastNetwork_Timepartsum', PACKAGE = 'MulticastNetwork', mumat, sigma_tau, senders, timestamps)
}

Timepartsum2 <- function(mumat, senders, timestamps) {
    .Call('_MulticastNetwork_Timepartsum2', PACKAGE = 'MulticastNetwork', mumat, senders, timestamps)
}

Timepartindiv <- function(mu, sigma_tau, timestamp) {
    .Call('_MulticastNetwork_Timepartindiv', PACKAGE = 'MulticastNetwork', mu, sigma_tau, timestamp)
}

multinom_vec <- function(x) {
    .Call('_MulticastNetwork_multinom_vec', PACKAGE = 'MulticastNetwork', x)
}

normalizer <- function(lambda_da) {
    .Call('_MulticastNetwork_normalizer', PACKAGE = 'MulticastNetwork', lambda_da)
}

Edgepartsum <- function(lambda, u) {
    .Call('_MulticastNetwork_Edgepartsum', PACKAGE = 'MulticastNetwork', lambda, u)
}

mu_cpp <- function(Y, eta) {
    .Call('_MulticastNetwork_mu_cpp', PACKAGE = 'MulticastNetwork', Y, eta)
}

mu_cpp_d <- function(Y, eta) {
    .Call('_MulticastNetwork_mu_cpp_d', PACKAGE = 'MulticastNetwork', Y, eta)
}

lambda_cpp <- function(X_d, beta) {
    .Call('_MulticastNetwork_lambda_cpp', PACKAGE = 'MulticastNetwork', X_d, beta)
}

sample_int <- function(n, min, max) {
    .Call('_MulticastNetwork_sample_int', PACKAGE = 'MulticastNetwork', n, min, max)
}

u_cpp <- function(lambda, u) {
    .Call('_MulticastNetwork_u_cpp', PACKAGE = 'MulticastNetwork', lambda, u)
}

u_cpp_d <- function(lambda_d, u) {
    .Call('_MulticastNetwork_u_cpp_d', PACKAGE = 'MulticastNetwork', lambda_d, u)
}

