# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sortuniq <- function(x) {
    .Call('_pkg_sortuniq', PACKAGE = 'pkg', x)
}

Mahalanobis <- function(x, center, cov) {
    .Call('_pkg_Mahalanobis', PACKAGE = 'pkg', x, center, cov)
}

ei <- function(M) {
    .Call('_pkg_ei', PACKAGE = 'pkg', M)
}

dmvnorm_arma <- function(x, mean, sigma) {
    .Call('_pkg_dmvnorm_arma', PACKAGE = 'pkg', x, mean, sigma)
}

rmvnorm_arma <- function(n, mu, Sigma) {
    .Call('_pkg_rmvnorm_arma', PACKAGE = 'pkg', n, mu, Sigma)
}

priorsum <- function(var, mu, x) {
    .Call('_pkg_priorsum', PACKAGE = 'pkg', var, mu, x)
}

tabulateC <- function(x, max) {
    .Call('_pkg_tabulateC', PACKAGE = 'pkg', x, max)
}

transpose <- function(x) {
    .Call('_pkg_transpose', PACKAGE = 'pkg', x)
}

callRMultinom <- function(x) {
    .Call('_pkg_callRMultinom', PACKAGE = 'pkg', x)
}

multinom_vec <- function(nSample, props) {
    .Call('_pkg_multinom_vec', PACKAGE = 'pkg', nSample, props)
}

which_int <- function(value, x) {
    .Call('_pkg_which_int', PACKAGE = 'pkg', value, x)
}

which_num <- function(value, x) {
    .Call('_pkg_which_num', PACKAGE = 'pkg', value, x)
}

rdirichlet_cpp <- function(num_samples, alpha_m) {
    .Call('_pkg_rdirichlet_cpp', PACKAGE = 'pkg', num_samples, alpha_m)
}

which_cpp <- function(value, x) {
    .Call('_pkg_which_cpp', PACKAGE = 'pkg', value, x)
}

expconst <- function(consts) {
    .Call('_pkg_expconst', PACKAGE = 'pkg', consts)
}

History <- function(edge, timestamps, A, d, timeunit) {
    .Call('_pkg_History', PACKAGE = 'pkg', edge, timestamps, A, d, timeunit)
}

History2 <- function(edge, timestamps, A, timeintd, timeunit) {
    .Call('_pkg_History2', PACKAGE = 'pkg', edge, timestamps, A, timeintd, timeunit)
}

Degree <- function(history, A, sender) {
    .Call('_pkg_Degree', PACKAGE = 'pkg', history, A, sender)
}

Outdegree <- function(timeintd, senders, A) {
    .Call('_pkg_Outdegree', PACKAGE = 'pkg', timeintd, senders, A)
}

Indegree <- function(history, A, sender) {
    .Call('_pkg_Indegree', PACKAGE = 'pkg', history, A, sender)
}

Dyadic <- function(history, A, sender) {
    .Call('_pkg_Dyadic', PACKAGE = 'pkg', history, A, sender)
}

Triadic <- function(history, A, sender) {
    .Call('_pkg_Triadic', PACKAGE = 'pkg', history, A, sender)
}

Netstats_cpp <- function(edge, timestamps, timeintd, senders, A, timeunit, netstat) {
    .Call('_pkg_Netstats_cpp', PACKAGE = 'pkg', edge, timestamps, timeintd, senders, A, timeunit, netstat)
}

inner <- function(x, y) {
    .Call('_pkg_inner', PACKAGE = 'pkg', x, y)
}

MultiplyXB <- function(X, B) {
    .Call('_pkg_MultiplyXB', PACKAGE = 'pkg', X, B)
}

lmultinom <- function(lprops) {
    .Call('_pkg_lmultinom', PACKAGE = 'pkg', lprops)
}

u_Gibbs <- function(u_di, lambda_di, delta, j) {
    .Call('_pkg_u_Gibbs', PACKAGE = 'pkg', u_di, lambda_di, delta, j)
}

Edgepart <- function(u, lambda, delta) {
    .Call('_pkg_Edgepart', PACKAGE = 'pkg', u, lambda, delta)
}

Edgepartsum <- function(X, B, u, delta) {
    .Call('_pkg_Edgepartsum', PACKAGE = 'pkg', X, B, u, delta)
}

mu_vec <- function(timemat, A, eta) {
    .Call('_pkg_mu_vec', PACKAGE = 'pkg', timemat, A, eta)
}

mu_mat <- function(timemat, A, eta) {
    .Call('_pkg_mu_mat', PACKAGE = 'pkg', timemat, A, eta)
}

Timepart <- function(mu, sigma_tau, a_d, t_d) {
    .Call('_pkg_Timepart', PACKAGE = 'pkg', mu, sigma_tau, a_d, t_d)
}

Timepartsum <- function(mumat, sigma_tau, senders, timestamps) {
    .Call('_pkg_Timepartsum', PACKAGE = 'pkg', mumat, sigma_tau, senders, timestamps)
}

timefinder <- function(timestamps, edgetrim, timeunit) {
    .Call('_pkg_timefinder', PACKAGE = 'pkg', timestamps, edgetrim, timeunit)
}

timefinder_vec <- function(timestamps, d, timeunit) {
    .Call('_pkg_timefinder_vec', PACKAGE = 'pkg', timestamps, d, timeunit)
}

